-- Seed products for MetroPrint USA
-- Run this in Supabase SQL Editor after running 001_initial.sql

INSERT INTO products (title, slug, category, description, base_price_text, image_url, options_schema, active) VALUES
('Custom T-Shirt Printing', 'custom-t-shirt-printing', 'Apparel', 'High-quality custom t-shirt printing for events, teams, and businesses.', 'Starting at $12/shirt', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["1","5","10","25","50","100"],"required":true},{"name":"shirt_color","label":"Shirt Color","type":"text","placeholder":"e.g. Navy, White, Black","required":true},{"name":"print_location","label":"Print Location","type":"select","options":["Front","Back","Front and Back"],"required":true},{"name":"size_breakdown","label":"Size Breakdown","type":"textarea","placeholder":"e.g. S:2, M:5, L:8, XL:3","required":false}]}', true),
('Custom Polo Printing', 'custom-polo-printing', 'Apparel', 'Professional embroidered or printed polos for corporate teams and events.', 'Starting at $18/polo', 'https://images.unsplash.com/photo-1622445275463-aba1ab721103?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["1","5","10","25","50","100"],"required":true},{"name":"polo_color","label":"Polo Color","type":"text","placeholder":"e.g. Navy, White","required":true},{"name":"print_location","label":"Print/Embroidery Location","type":"select","options":["Left Chest","Full Front","Back","Sleeve"],"required":true},{"name":"size_breakdown","label":"Size Breakdown","type":"textarea","placeholder":"e.g. S:2, M:5, L:8","required":false}]}', true),
('Custom Hoodie Printing', 'custom-hoodie-printing', 'Apparel', 'Premium hoodie printing for brands, schools, and organizations.', 'Starting at $28/hoodie', 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["1","5","10","25","50","100"],"required":true},{"name":"hoodie_color","label":"Hoodie Color","type":"text","placeholder":"e.g. Black, Gray, Navy","required":true},{"name":"print_location","label":"Print Location","type":"select","options":["Front","Back","Front and Back"],"required":true},{"name":"size_breakdown","label":"Size Breakdown","type":"textarea","placeholder":"e.g. S:2, M:5, L:8, XL:3","required":false}]}', true),
('Custom Hats', 'custom-hats', 'Apparel', 'Embroidered or printed caps, beanies, and trucker hats for your brand.', 'Starting at $10/hat', 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["12","24","48","72","144"],"required":true},{"name":"hat_style","label":"Hat Style","type":"select","options":["Structured Cap","Trucker Hat","Beanie","Snapback"],"required":true},{"name":"hat_color","label":"Hat Color","type":"text","placeholder":"e.g. Black, Navy, Khaki","required":true}]}', true),
('Tote Bags', 'tote-bags', 'Apparel', 'Custom printed tote bags for retail, events, and promotional giveaways.', 'Starting at $8/bag', 'https://images.unsplash.com/photo-1591562555315-8019a069fd93?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["25","50","100","250","500"],"required":true},{"name":"bag_color","label":"Bag Color","type":"text","placeholder":"e.g. Natural, Black, Navy","required":true},{"name":"print_sides","label":"Print Sides","type":"select","options":["One Side","Both Sides"],"required":true}]}', true),
('Business Cards', 'business-cards', 'Print Materials', 'Premium business cards with matte, glossy, or soft-touch finishes.', 'Starting at $29/500', 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"finish","label":"Finish","type":"select","options":["Matte","Glossy","Soft Touch"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true),
('Flyers', 'flyers', 'Print Materials', 'Eye-catching flyers for promotions, events, and marketing campaigns.', 'Starting at $49/500', 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000"],"required":true},{"name":"size","label":"Size","type":"select","options":["8.5\" x 11\"","5.5\" x 8.5\"","4\" x 6\""],"required":true},{"name":"paper_type","label":"Paper Type","type":"select","options":["100lb Gloss","100lb Matte","80lb Text"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true}]}', true),
('Brochures', 'brochures', 'Print Materials', 'Tri-fold and bi-fold brochures to showcase your products and services.', 'Starting at $89/250', 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000"],"required":true},{"name":"size","label":"Size","type":"select","options":["8.5\" x 11\" Tri-Fold","11\" x 17\" Bi-Fold"],"required":true},{"name":"paper_type","label":"Paper Type","type":"select","options":["100lb Gloss","100lb Matte","80lb Text"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true}]}', true),
('Posters', 'posters', 'Print Materials', 'Large format posters for retail, events, and advertising.', 'Starting at $15/poster', 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["1","5","10","25","50","100"],"required":true},{"name":"size","label":"Size","type":"select","options":["18\" x 24\"","24\" x 36\"","11\" x 17\""],"required":true},{"name":"paper_type","label":"Paper Type","type":"select","options":["Glossy","Matte","Satin"],"required":true}]}', true),
('Door Hangers', 'door-hangers', 'Print Materials', 'Door hanger marketing for local promotions and service businesses.', 'Starting at $59/500', 'https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["250","500","1000","2500","5000"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true),
('Bookmarks', 'bookmarks', 'Print Materials', 'Custom bookmarks for libraries, schools, and promotional campaigns.', 'Starting at $39/500', 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["100","250","500","1000","2500"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true),
('Folders', 'folders', 'Print Materials', 'Presentation folders with pockets for sales materials and proposals.', 'Starting at $99/100', 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true),
('Roll-Up Banners', 'roll-up-banners', 'Print Materials', 'Portable roll-up banners for trade shows, events, and retail displays.', 'Starting at $89/banner', 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["1","2","3","5","10"],"required":true},{"name":"size","label":"Size","type":"select","options":["33\" x 80\"","24\" x 72\""],"required":true}]}', true),
('Custom Mugs', 'custom-mugs', 'Promotional Products', 'Branded ceramic mugs for corporate gifts and promotional campaigns.', 'Starting at $8/mug', 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["12","24","48","72","144"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true),
('Custom Tumblers', 'custom-tumblers', 'Promotional Products', 'Insulated tumblers with your logo for lasting brand visibility.', 'Starting at $12/tumbler', 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["12","24","48","72","144"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true),
('Branded Merchandise', 'branded-merchandise', 'Promotional Products', 'Custom branded merchandise packages for events, clients, and employees.', 'Custom pricing', 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Estimated Quantity","type":"select","options":["25","50","100","250","500+"],"required":true},{"name":"item_types","label":"Item Types Needed","type":"textarea","placeholder":"e.g. Pens, notebooks, USB drives","required":true},{"name":"budget","label":"Budget Range","type":"text","placeholder":"e.g. $500–$1,000","required":false}]}', true),
('DTF Transfers', 'dtf-transfers', 'DTF Printing', 'Direct-to-film transfers for vibrant, durable prints on any fabric color.', 'Starting at $3/transfer', 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["10","25","50","100","250","500"],"required":true},{"name":"transfer_size","label":"Transfer Size","type":"select","options":["4\" x 4\"","8\" x 10\"","11\" x 11\"","Custom"],"required":true}]}', true),
('Custom Apparel Printing (DTF)', 'custom-apparel-printing-dtf', 'DTF Printing', 'Full custom apparel printing using DTF technology for any garment.', 'Starting at $15/piece', 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["1","5","10","25","50","100"],"required":true},{"name":"garment_type","label":"Garment Type","type":"text","placeholder":"e.g. T-shirt, Hoodie","required":true},{"name":"print_location","label":"Print Location","type":"select","options":["Front","Back","Front and Back","Sleeve"],"required":true},{"name":"size_breakdown","label":"Size Breakdown","type":"textarea","placeholder":"e.g. S:2, M:5, L:8","required":false}]}', true),
('Graphic Design Services', 'graphic-design-services', 'Marketing Services', 'Professional graphic design for print, digital, and brand materials.', 'Starting at $75/hr', 'https://images.unsplash.com/photo-1561070791-2520d4200b47?w=800&h=600&fit=crop', '{"fields":[{"name":"project_type","label":"Project Type","type":"select","options":["Logo Design","Print Design","Social Media Graphics","Packaging","Other"],"required":true},{"name":"deadline","label":"Desired Deadline","type":"text","placeholder":"e.g. 2 weeks","required":false}]}', true),
('Branding', 'branding', 'Marketing Services', 'Complete brand identity packages including logo, colors, and guidelines.', 'Packages from $499', 'https://images.unsplash.com/photo-1558655146-d09347e92766?w=800&h=600&fit=crop', '{"fields":[{"name":"package_level","label":"Package Level","type":"select","options":["Starter","Professional","Enterprise"],"required":true},{"name":"deliverables","label":"Deliverables Needed","type":"textarea","placeholder":"e.g. Logo, business cards, brand guide","required":true}]}', true),
('Social Media Management', 'social-media-management', 'Marketing Services', 'Consistent social media content and management to grow your brand online.', 'Plans from $299/mo', 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=600&fit=crop', '{"fields":[{"name":"platforms","label":"Platforms","type":"text","placeholder":"e.g. Instagram, Facebook, LinkedIn","required":true},{"name":"posting_frequency","label":"Posting Frequency","type":"select","options":["3 posts/week","5 posts/week","Daily"],"required":true}]}', true),
('Video Production', 'video-production', 'Marketing Services', 'Professional video production for commercials, promos, and social content.', 'Projects from $999', 'https://images.unsplash.com/photo-1492691527719-9d1e37e684fb?w=800&h=600&fit=crop', '{"fields":[{"name":"video_type","label":"Video Type","type":"select","options":["Commercial","Promotional","Social Media","Event Coverage","Other"],"required":true},{"name":"duration","label":"Estimated Duration","type":"text","placeholder":"e.g. 30 seconds, 2 minutes","required":false}]}', true),
('Content Creation', 'content-creation', 'Marketing Services', 'Blog posts, copywriting, and content strategy for your business.', 'Starting at $50/piece', 'https://images.unsplash.com/photo-1455390572245-444bebb8ee83?w=800&h=600&fit=crop', '{"fields":[{"name":"content_type","label":"Content Type","type":"select","options":["Blog Posts","Website Copy","Email Campaigns","Product Descriptions","Other"],"required":true},{"name":"quantity","label":"Number of Pieces","type":"select","options":["1","5","10","Ongoing"],"required":true}]}', true)
ON CONFLICT (slug) DO NOTHING;

-- Business Cards category products (requires subcategory column from migration)
INSERT INTO products (title, slug, category, subcategory, description, base_price_text, image_url, options_schema, active) VALUES
('Matte Business Cards', 'bc-standard-matte', 'Business Cards', 'Standard', 'Classic matte finish business cards with a smooth, non-reflective surface.', 'Contact for pricing', 'https://images.pexels.com/photos/4862950/pexels-photo-4862950.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"size","label":"Size","type":"select","options":["3.5\" x 2\" (Standard)","3.5\" x 2.5\"","2\" x 2\" (Square)"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"turnaround","label":"Turnaround","type":"select","options":["Standard (5-7 days)","Rush (2-3 days)","Same Day"],"required":true}]}', true),
('UV Gloss Business Cards', 'bc-standard-uv-gloss', 'Business Cards', 'Standard', 'High-shine UV coated business cards that make colors pop.', 'Contact for pricing', 'https://images.pexels.com/photos/5706020/pexels-photo-5706020.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"size","label":"Size","type":"select","options":["3.5\" x 2\" (Standard)","3.5\" x 2.5\"","2\" x 2\" (Square)"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"turnaround","label":"Turnaround","type":"select","options":["Standard (5-7 days)","Rush (2-3 days)","Same Day"],"required":true}]}', true),
('Metallic Foil (Raised) Business Cards', 'bc-premium-metallic-foil-raised', 'Business Cards', 'Premium', 'Luxurious raised metallic foil business cards with a tactile, premium feel.', 'Contact for pricing', 'https://images.pexels.com/photos/6149103/pexels-photo-6149103.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000"],"required":true},{"name":"foil_color","label":"Foil Color","type":"select","options":["Gold","Silver","Rose Gold","Copper","Holographic"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"turnaround","label":"Turnaround","type":"select","options":["Standard (7-10 days)","Rush (4-5 days)"],"required":true}]}', true),
('Kraft Paper Business Cards', 'bc-premium-kraft-paper', 'Business Cards', 'Premium', 'Eco-friendly kraft paper business cards with a natural, rustic aesthetic.', 'Contact for pricing', 'https://images.pexels.com/photos/8250871/pexels-photo-8250871.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500"],"required":true},{"name":"printing","label":"Printing","type":"select","options":["Full Color","Black Ink Only","White Ink"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"turnaround","label":"Turnaround","type":"select","options":["Standard (5-7 days)","Rush (2-3 days)"],"required":true}]}', true),
('Durable Business Cards', 'bc-premium-durable', 'Business Cards', 'Premium', 'Extra-thick, tear-resistant business cards built to last.', 'Contact for pricing', 'https://images.pexels.com/photos/8066713/pexels-photo-8066713.png?auto=compress&cs=tinysrgb&h=650&w=940', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"turnaround","label":"Turnaround","type":"select","options":["Standard (5-7 days)","Rush (2-3 days)"],"required":true}]}', true),
('Spot UV (Raised) Business Cards', 'bc-premium-spot-uv-raised', 'Business Cards', 'Premium', 'Dramatic contrast between matte and glossy with raised spot UV coating.', 'Contact for pricing', 'https://images.pexels.com/photos/5706018/pexels-photo-5706018.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"turnaround","label":"Turnaround","type":"select","options":["Standard (7-10 days)","Rush (4-5 days)"],"required":true}]}', true),
('Pearl Paper Business Cards', 'bc-premium-pearl-paper', 'Business Cards', 'Premium', 'Shimmering pearl finish business cards with an iridescent sheen.', 'Contact for pricing', 'https://images.pexels.com/photos/346553/pexels-photo-346553.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"turnaround","label":"Turnaround","type":"select","options":["Standard (5-7 days)","Rush (2-3 days)"],"required":true}]}', true),
('Die Cut Business Cards', 'bc-premium-die-cut', 'Business Cards', 'Premium', 'Custom-shaped business cards cut to your unique design.', 'Contact for pricing', 'https://images.pexels.com/photos/5705980/pexels-photo-5705980.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["100","250","500","1000"],"required":true},{"name":"shape","label":"Shape","type":"select","options":["Rounded Corners","Circle","Half Circle","Leaf","Custom Shape"],"required":true},{"name":"turnaround","label":"Turnaround","type":"select","options":["Standard (7-10 days)","Rush (4-5 days)"],"required":true}]}', true),
('Soft Touch (Suede) Business Cards', 'bc-premium-soft-touch-suede', 'Business Cards', 'Premium', 'Velvety soft-touch laminated business cards with a luxurious suede-like texture.', 'Contact for pricing', 'https://images.pexels.com/photos/4862926/pexels-photo-4862926.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"turnaround","label":"Turnaround","type":"select","options":["Standard (5-7 days)","Rush (2-3 days)"],"required":true}]}', true),
('32pt Painted Edge Business Cards', 'bc-premium-32pt-painted-edge', 'Business Cards', 'Premium', 'Ultra-thick 32pt cardstock with vibrant painted edges.', 'Contact for pricing', 'https://images.pexels.com/photos/9878733/pexels-photo-9878733.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000"],"required":true},{"name":"edge_color","label":"Edge Color","type":"select","options":["Gold","Silver","Red","Blue","Black","Green","Custom"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"turnaround","label":"Turnaround","type":"select","options":["Standard (7-10 days)","Rush (4-5 days)"],"required":true}]}', true),
('Ultra Smooth Business Cards', 'bc-premium-ultra-smooth', 'Business Cards', 'Premium', 'Premium uncoated ultra-smooth cardstock for a clean, modern look.', 'Contact for pricing', 'https://images.pexels.com/photos/11149812/pexels-photo-11149812.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"turnaround","label":"Turnaround","type":"select","options":["Standard (5-7 days)","Rush (2-3 days)"],"required":true}]}', true),
('Fold Over Business Cards', 'bc-specialty-fold-over', 'Business Cards', 'Specialty', 'Double-sized cards that fold to standard size for twice the space.', 'Contact for pricing', 'https://images.pexels.com/photos/9869077/pexels-photo-9869077.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000"],"required":true},{"name":"fold","label":"Fold Direction","type":"select","options":["Horizontal","Vertical"],"required":true},{"name":"turnaround","label":"Turnaround","type":"select","options":["Standard (7-10 days)","Rush (4-5 days)"],"required":true}]}', true),
('Plastic Business Cards', 'bc-specialty-plastic', 'Business Cards', 'Specialty', 'Transparent or frosted plastic business cards that are waterproof and virtually indestructible.', 'Contact for pricing', 'https://images.pexels.com/photos/7821730/pexels-photo-7821730.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000"],"required":true},{"name":"material","label":"Material","type":"select","options":["Clear Plastic","Frosted Plastic","White Plastic","Black Plastic"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"turnaround","label":"Turnaround","type":"select","options":["Standard (10-14 days)","Rush (5-7 days)"],"required":true}]}', true),
('Magnetic Business Cards', 'bc-specialty-magnetic', 'Business Cards', 'Specialty', 'Business cards with a magnetic backing that stick to fridges and metal surfaces.', 'Contact for pricing', 'https://images.pexels.com/photos/15569097/pexels-photo-15569097.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500"],"required":true},{"name":"turnaround","label":"Turnaround","type":"select","options":["Standard (7-10 days)","Rush (4-5 days)"],"required":true}]}', true)
ON CONFLICT (slug) DO NOTHING;

-- Deactivate old generic business cards product now that we have the full category
UPDATE products SET active = false WHERE slug = 'business-cards' AND category = 'Print Materials';

-- Keep Business Cards imagery current (safe to re-run)
UPDATE products
SET image_url = CASE slug
  WHEN 'bc-standard-matte' THEN 'https://images.pexels.com/photos/4862950/pexels-photo-4862950.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'
  WHEN 'bc-standard-uv-gloss' THEN 'https://images.pexels.com/photos/5706020/pexels-photo-5706020.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'
  WHEN 'bc-premium-metallic-foil-raised' THEN 'https://images.pexels.com/photos/6149103/pexels-photo-6149103.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'
  WHEN 'bc-premium-kraft-paper' THEN 'https://images.pexels.com/photos/8250871/pexels-photo-8250871.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'
  WHEN 'bc-premium-durable' THEN 'https://images.pexels.com/photos/8066713/pexels-photo-8066713.png?auto=compress&cs=tinysrgb&h=650&w=940'
  WHEN 'bc-premium-spot-uv-raised' THEN 'https://images.pexels.com/photos/5706018/pexels-photo-5706018.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'
  WHEN 'bc-premium-pearl-paper' THEN 'https://images.pexels.com/photos/346553/pexels-photo-346553.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'
  WHEN 'bc-premium-die-cut' THEN 'https://images.pexels.com/photos/5705980/pexels-photo-5705980.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'
  WHEN 'bc-premium-soft-touch-suede' THEN 'https://images.pexels.com/photos/4862926/pexels-photo-4862926.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'
  WHEN 'bc-premium-32pt-painted-edge' THEN 'https://images.pexels.com/photos/9878733/pexels-photo-9878733.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'
  WHEN 'bc-premium-ultra-smooth' THEN 'https://images.pexels.com/photos/11149812/pexels-photo-11149812.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'
  WHEN 'bc-specialty-fold-over' THEN 'https://images.pexels.com/photos/9869077/pexels-photo-9869077.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'
  WHEN 'bc-specialty-plastic' THEN 'https://images.pexels.com/photos/7821730/pexels-photo-7821730.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'
  WHEN 'bc-specialty-magnetic' THEN 'https://images.pexels.com/photos/15569097/pexels-photo-15569097.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'
  ELSE image_url
END
WHERE category = 'Business Cards';

-- Remove unsupported stock/finish option fields from Business Cards (safe to re-run)
UPDATE products
SET options_schema = jsonb_set(
  options_schema,
  '{fields}',
  COALESCE(
    (
      SELECT jsonb_agg(field)
      FROM jsonb_array_elements(options_schema->'fields') AS field
      WHERE COALESCE(field->>'name', '') NOT IN ('stock', 'finish')
    ),
    '[]'::jsonb
  ),
  true
)
WHERE category = 'Business Cards';
