-- Business Cards category (MetroPrint USA MKT1)
-- Deactivate legacy single business-cards product under Print Materials

UPDATE products SET active = false WHERE slug = 'business-cards';

-- Standard
INSERT INTO products (title, slug, category, description, base_price_text, image_url, options_schema, active, price) VALUES
('Standard Matte Business Cards', 'business-cards-standard-matte', 'Business Cards', 'Standard Matte business cards from MetroPrint USA (MKT1). Upload your artwork, choose quantity and sides, and checkout online.', 'Starting at $29/500', 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"finish","label":"Card Type","type":"select","options":["Matte"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true, 29.99),
('Standard UV Gloss Business Cards', 'business-cards-standard-uv-gloss', 'Business Cards', 'Standard UV Gloss business cards from MetroPrint USA (MKT1). Upload your artwork, choose quantity and sides, and checkout online.', 'Starting at $29/500', 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"finish","label":"Card Type","type":"select","options":["UV Gloss"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true, 29.99)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  base_price_text = EXCLUDED.base_price_text,
  options_schema = EXCLUDED.options_schema,
  active = EXCLUDED.active,
  price = EXCLUDED.price;

-- Premium
INSERT INTO products (title, slug, category, description, base_price_text, image_url, options_schema, active, price) VALUES
('Premium Metallic Foil (Raised) Business Cards', 'business-cards-premium-metallic-foil-raised', 'Business Cards', 'Premium Metallic Foil (Raised) business cards from MetroPrint USA (MKT1).', 'Starting at $29/500', 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"finish","label":"Card Type","type":"select","options":["Metallic Foil (Raised)"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true, 34.99),
('Premium Kraft Paper Business Cards', 'business-cards-premium-kraft-paper', 'Business Cards', 'Premium Kraft Paper business cards from MetroPrint USA (MKT1).', 'Starting at $29/500', 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"finish","label":"Card Type","type":"select","options":["Kraft Paper"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true, 32.99),
('Premium Durable Business Cards', 'business-cards-premium-durable', 'Business Cards', 'Premium Durable business cards from MetroPrint USA (MKT1).', 'Starting at $29/500', 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"finish","label":"Card Type","type":"select","options":["Durable"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true, 32.99),
('Premium Spot UV (Raised) Business Cards', 'business-cards-premium-spot-uv-raised', 'Business Cards', 'Premium Spot UV (Raised) business cards from MetroPrint USA (MKT1).', 'Starting at $29/500', 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"finish","label":"Card Type","type":"select","options":["Spot UV (Raised)"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true, 34.99),
('Premium Pearl Paper Business Cards', 'business-cards-premium-pearl-paper', 'Business Cards', 'Premium Pearl Paper business cards from MetroPrint USA (MKT1).', 'Starting at $29/500', 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"finish","label":"Card Type","type":"select","options":["Pearl Paper"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true, 32.99),
('Premium Die Cut Business Cards', 'business-cards-premium-die-cut', 'Business Cards', 'Premium Die Cut business cards from MetroPrint USA (MKT1).', 'Starting at $29/500', 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"finish","label":"Card Type","type":"select","options":["Die Cut"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true, 36.99),
('Premium Soft Touch (Suede) Business Cards', 'business-cards-premium-soft-touch-suede', 'Business Cards', 'Premium Soft Touch (Suede) business cards from MetroPrint USA (MKT1).', 'Starting at $29/500', 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"finish","label":"Card Type","type":"select","options":["Soft Touch (Suede)"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true, 34.99),
('Premium 32pt Painted Edge Business Cards', 'business-cards-premium-32pt-painted-edge', 'Business Cards', 'Premium 32pt Painted Edge business cards from MetroPrint USA (MKT1).', 'Starting at $29/500', 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"finish","label":"Card Type","type":"select","options":["32pt Painted Edge"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true, 39.99),
('Premium Ultra Smooth Business Cards', 'business-cards-premium-ultra-smooth', 'Business Cards', 'Premium Ultra Smooth business cards from MetroPrint USA (MKT1).', 'Starting at $29/500', 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"finish","label":"Card Type","type":"select","options":["Ultra Smooth"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true, 32.99)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  base_price_text = EXCLUDED.base_price_text,
  options_schema = EXCLUDED.options_schema,
  active = EXCLUDED.active,
  price = EXCLUDED.price;

-- Specialty
INSERT INTO products (title, slug, category, description, base_price_text, image_url, options_schema, active, price) VALUES
('Specialty Fold Over Business Cards', 'business-cards-specialty-fold-over', 'Business Cards', 'Specialty Fold Over business cards from MetroPrint USA (MKT1).', 'Starting at $29/500', 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"finish","label":"Card Type","type":"select","options":["Fold Over"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true, 36.99),
('Specialty Plastic Business Cards', 'business-cards-specialty-plastic', 'Business Cards', 'Specialty Plastic business cards from MetroPrint USA (MKT1).', 'Starting at $29/500', 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"finish","label":"Card Type","type":"select","options":["Plastic"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true, 34.99),
('Specialty Magnetic Business Cards', 'business-cards-specialty-magnetic', 'Business Cards', 'Specialty Magnetic business cards from MetroPrint USA (MKT1).', 'Starting at $29/500', 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop', '{"fields":[{"name":"quantity","label":"Quantity","type":"select","options":["50","100","250","500","1000","2500","5000"],"required":true},{"name":"finish","label":"Card Type","type":"select","options":["Magnetic"],"required":true},{"name":"sides","label":"Sides","type":"select","options":["Single Sided","Double Sided"],"required":true},{"name":"need_design_help","label":"Need Design Help","type":"radio","options":["Yes","No"],"required":true}]}', true, 39.99)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  base_price_text = EXCLUDED.base_price_text,
  options_schema = EXCLUDED.options_schema,
  active = EXCLUDED.active,
  price = EXCLUDED.price;
